### ISSUE TITLE
[8.0] [stock_ownership_availability_rules] Incompatible with real-time inventory valuation

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/stock-logistics-workflow#197]
Module 'stock_ownership_availability_rules' sets an owner to the quant, even when the quant belongs to the company. However module "stock_account" in method "_account_entry_move" will define that if the quant has an owner, it assumes that the owner is a third party, regardless if the actual owner IS the company.

**Comment by jgrandguillaume** [comment]
Hi,

That's sad... I tend to think, looking at this module, that we can get rid of it. I think we should not force to set the owner if it belong to the company.

The main purpose of this module is to ensure not to take stock from another company when delivering goods.

My2cents,

Joël

**Comment by laetitia-gangloff** [comment]
Not directly related to this issue, but related to the module stock_ownership_availability_rules. I reported the following PR : https://github.com/OCA/stock-logistics-workflow/pull/195

The button "update quantity" is not compatible with this module, because the generated inventory do not set owner on line, and the theorical quantity is computed on quants with the same owner than inventory line.

**Comment by JordiBForgeFlow** [comment]
In order to solve this issue, I propose to add a separate module 'stock_account_ownership_availability_rules" that solves this issue. What do you think?

**Comment by yostashiro** [comment]
@jbeficent I made this PR https://github.com/OCA/stock-logistics-workflow/pull/100 before to fix the issue.  Haven't had the time to properly follow up.

**Comment by andhit-r** [comment]
I confirm this issue. @jbeficent would you share your idea?
