### ISSUE TITLE
Documentation / Screenshots for workflows

### ISSUE THREAD

**Issue by rmehta** [OCA/stock-logistics-workflow#290]
Hello is there a way to find documentation / screenshots for this module? I searched online but was not able to find it.

**Comment by pedrobaeza** [comment]
Hi, Rhushab, there are a lot of modules inside this repository. Are you talking about one in particular?

**Comment by rmehta** [comment]
In general?  We are planning to upgrade manufacturing module in ERPNext and thought this might be a good reference point. Relevant discussion: https://discuss.erpnext.com/t/enhancing-the-manufacturing-module/18401/29

If there is no documentation, maybe I can get someone to take a screenshots and post it on the wiki?

**Comment by lasley** [comment]
@rmehta - Each module is managed independently, and all screenshots would be in the `ReadMe.rst` inside of each folder inside of this repo. 

We also have a runbot, which allow for functional testing. The link should be located inside of each ReadMe.

In most instances this documentation is slim, particularly in terms of screenshots. Help is always welcome!

I'm going to close this issue, because I think I have answered your question. Please let us know if that's not the case.
