### ISSUE TITLE
8.0: stock_cancel breaks stock levels

### ISSUE THREAD

**Issue by alexis-via** [OCA/stock-logistics-workflow#59]
Here is the scenario with an up-to-date code on odoo v8:
- install the stock_cancel module
- we will use the demo product "USB Headset", which doesn't have any stock move in the demo data
- On the product form of USB headset, click on "Update" next to the Quantity on hand and set a qty of 10.
- Create a new sale order with 1 sale order line with 2 USB headset. Confirm it and transfer the picking. Now, the "Quantity on hand" for USB Headset = 8.
- On the picking, click on the "Re-open" button. The "Quantity on hand" for USB Headset = 8 ; it should be 10 ! It's a bug.

**Comment by alexis-via** [comment]
If you continue the scenario and you re-transfer the picking, the "Quantity on hand" for USB Headset = 6 (it should be 8).

**Comment by pedrobaeza** [comment]
Please directly disable the module until we fix this.

**Comment by alexis-via** [comment]
@pedrobaeza I don't have commit rights, so I leave you do that. We urgently need to fix the bad data to restore good stock levels (I'm working on this at the moment, help appreciated) ; and we also need to fix the bug of course.

**Comment by alexis-via** [comment]
The issue is clearly linked to the fact that we don't take into account the stock.quant object when we re-open a picking. But it's still unclear to me what a stock.quant represent in v8. Do you know ?

**Comment by pedrobaeza** [comment]
OK, I'll do it in a couple of hours and investigate the best way to do it.

**Comment by pedrobaeza** [comment]
I have put it as not installable in https://github.com/OCA/stock-logistics-workflow/commit/533bb1a3e3d845a84c3f897cb490df02fb11a71f.

**Comment by alexis-via** [comment]
@pedrobaeza 
OK, good. Now, we urgently need to find a way to fix the bad stock.quants. I started to work on it, but it's really not easy at all. I dream that we could delete all stock quants and re-generate them all, but I'm not sure we can do that.

**Comment by pedrobaeza** [comment]
Yeah, in a first glance, I see that the problem is the propagation of the data across stock.quants. Maybe first restrict this cancel only for the base case (this stock hasn't been used)?

**Comment by jgrandguillaume** [comment]
Hi,

I don't think we can ever re-create all the quants because they don't contain only quantity information, but prices that are stored only there. So if you drop them, you lose this valuable information (and may other).

This is why we should not be able to cancel a picking IMO. It was ok before quants appear, but now, it'll introduce quite a lot of trouble.

This module may want to implement a reverse picking + a new version of the picking. So the user make the operation in one click, but the resulte is:
- Original picking : Done
- Reverse picking : Done
- New picking : Confirmed

This way we'll spare all the logic needed to don't mess up all the quants, what do you think ? Do I miss something ?

Regards,

**Comment by alexis-via** [comment]
@jgrandguillaume 
I agree with you ; stock_cancel was working fine on versions before v8 i.e. before stock.quant was introduced ; now it's not possible any more. I have uninstalled the module on the Odoo v8 server of my customer where it was installed.

But my question today is the following: I have wrong stock levels caused by the use of stock_cancel during a few weeks in a production database ; how can I fix this ? My idea was to delete all stock.quant and re-generate them all, but I don't see an easy way to regenerate all stock.quant. So I'm looking for other ideas... all good ideas are welcomed.

**Comment by lepistone** [comment]
I'm sorry I did some code review but I didn't notice the fundamental problem with this. Indeed in v8 validating moves does many complex things -- it makes stock reservations, creates, splits and moves quants, among others.

A quant represents information about a few specific items in stock, and allows us to distinguish this item that we bough yesterday for $400 from that other one we got from someone else last week for $350. That information is used for things like stock reservation, LIFO/FIFO and traceability.

Moreover, `stock_cancel` actually allows to "reopen" (not to cancel), both from 'cancel' and from 'done' status.

Maybe the change 'cancel' to 'draft' could be allowed, because it does not affect stock. On the other hand, the change from 'done' to 'draft' should not be allowed without taking care of quants logic which is probably too complex to make sense.

As for the inconsistent databases, @alexis-via, I'm not completely sure, but I wouldn't delete all quants. If you don't have too many products, you can probably compare the stock reported by odoo (that counts quants) with the stock computed à la v7 (i. e. counting incoming - outgoing moves for your product, to/from your location). And then you could manually create of delete a quant to get back to normal.

**Comment by anajuaristi** [comment]
Hello:

To recreate the correct inventory for products you only need to make that... an inventory. Even if you delete all quants, your inventory will recreate all of them and if I'm not mistaken, inventory will be valuated using each product avg cost from its form record

I could not exactly give the definition of a quant but it basically collects relation between 
product quantity location lot and package giving exact valuation of that product/lot/package on that location 

Before quants those data where calculated "on the fly" just recalculating stock moves- In V8 this aproach has been totally refactored and heavily improved. I have got to say that I like very much quant aproach.

Now.. a quant is generated when an stock is created in a location. If you make done incoming movement from supplier it will create a quant with mentioned data related to stock.move destiny location. Let's say destiny1.
So.. if you move some units from destiny1 to destiny2, a new quant will appair on second location. If you move ALL units from destiny1 to destiny2, first quant simply desappair from quants. That allows user just going to quants and exactly know what you have and where with it's proper valuation.
Quants are also created when movement destiy location is virtual so your real stock will be only the one related to phisical locations on quants. 

At the end a new concept appairs on "reservation" FIfo and Lifo methods. 
If you need to take some materials from origin to move to destiny you need to assing a quant to stock.move. This is quant reservation. An example:
In outgoing movement you need 100 units to be send form stock to customer
You have got a single 150 unit quant related to stock location
Never mind lifo or fifo methods on this case since you have got a single quant that could cover your material need. 
If you push check availability on picking or move that single quant will be splitted in 2 quants one with 100 units that will be assigned to movement and second 50 units that it's still "free" to be assigned later. 
When movement is done, 100 units quant will desapair and simply will appair on customer location.

It's brilliant. The single thing I don't like is that splitted quants never regroup again. That is if you push unassign on first assigned quant you will still have 2 quants forever and never will have a single one "free" with 150units. This is the only anoying thing with quants. So sometimes few small "identical" quants will be assigned to cover a material need on origin instead of assigning a single one but it's a small usability issue.

Exactly same behavior is provided for trazeable products/quants. You will always now the real quantity of products by lot. That was very unstable on old odoo versions. Now I find it works really well. 

Wishing this could help:

Thank you everybody
Ana

**Comment by anajuaristi** [comment]
About @jgrandguillaume proposal, I think he gave me a very simple idea... Let me share with you... 

Joels proposal will be functionally correct... 
Supose done movement origin= location1, destiny=location2
First stock picking would create one quant on location2 and would make desappair quant in location1
Second one (reverse) would create one quant on location1 and would make desapair quant in location2.

So... IMHO the correct way to make stock_cancel or make a movement "undone" would be simply assigning to quant stock.move Origin location, You just need moving or creating again stock on origin so I think It would work. 
On example done stock.move would create quant on location2(destiny location)
if Undone simply changes location2 for location1 I thik it would be right. 

Not very complex programming needed, undone movement would make just the opposite to done movement related to quants
Opinions?

**Comment by jgrandguillaume** [comment]
@alexis-via I think I would go for the Ana's solution: make an inventory. This would correct the data. If I had to do it, I would make a script using Erppeek (https://pypi.python.org/pypi/ERPpeek):

1) Compute for every product / location the quantity using the stock.move

2) Create an inventory for every product/location according to the result of 1)

3) Post the inventory

This way, your stock level will be fine. So don't worry, it's gonna be alright :) The only limitation is that you may not have a proper value on your quants if you are using the "Real cost" method, if you're on avarage costing method, it's fine.

Good luck,

**Comment by eLBati** [comment]
Hi all, following @anajuaristi idea, here is my proposal https://github.com/OCA/stock-logistics-workflow/pull/72

**Comment by eLBati** [comment]
About reopening cancelled pickings, I opened https://github.com/OCA/stock-logistics-workflow/pull/222
