### ISSUE TITLE
Current 12.0 fails because of stock_picking_package_preparation_line

### ISSUE THREAD

**Issue by bealdav** [OCA/stock-logistics-workflow#792]
Hi all,

The module stock_picking_package_preparation_line fails in current branch

see this empty PR
https://github.com/OCA/stock-logistics-workflow/pull/790

with https://travis-ci.com/github/OCA/stock-logistics-workflow/jobs/485838053#L2061

I'm not familiar with this module

Please @SimoRubi @archetipo @eLBati @tafaRU @rousseldenis could you help me ?

Have you an idea ?

**Comment by rousseldenis** [comment]
At first sight, I would say that two quants have been created instead of one with a quantity of 2.

**Comment by rousseldenis** [comment]
Maybe if product has been changed to tracking == "serial"

**Comment by eLBati** [comment]
What happened after the last green build of 12.0 https://travis-ci.com/github/OCA/stock-logistics-workflow/builds/214027420 ?

**Comment by bealdav** [comment]
Good question

**Comment by bealdav** [comment]
Because this module fails alone it's probably a change in odoo itself since last green build. A event which can occurs in other circumstances.

**Comment by grindtildeath** [comment]
@bealdav @eLBati @rousseldenis I gave a look into this issue since travis is failing on my PR #816 

It is indeed a commit in Odoo that is breaking the tests:
https://github.com/odoo/odoo/commit/3bbefb10866c6bb1ff8772c8c6e7bdce70d7cf5a

I cannot understand how Odoo does such a change on `stock.quant._gather` function as it introduces an OR on the `lot_id` parameter and returns quants with the lot passed as a parameter and quants without lots...

I did a temp fix in following PR: https://github.com/OCA/stock-logistics-workflow/pull/817

**Comment by bealdav** [comment]
Thanks a lot @grindtildeath good catch
